---
resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.0/deploy/static/provider/baremetal/deploy.yaml

patches:
  - path: ./service-patch.yaml
    target:
      kind: Service
      name: ingress-nginx-controller
