
@protocol=http
@url=kube001.informatik.intern.uni-leipzig.de
@port=30104


PUT {{protocol}}://{{url}}:{{port}}/project/register
content-type: application/json

{
    "config": "asdf"
}
###
DELETE {{protocol}}://{{url}}:{{port}}/project/delete/123
###


PUT {{protocol}}://{{url}}:{{port}}/config/add/5
content-type: application/json

{
    "config": "asdf"
}
###
GET {{protocol}}://{{url}}:{{port}}/config/get/1?config_id=123
###
GET {{protocol}}://{{url}}:{{port}}/config/get_all/1
###


POST {{protocol}}://{{url}}:{{port}}/test/commit/1?commit=cc46701e747d855807c26252c90b628c9cd319cc
###
GET {{protocol}}://{{url}}:{{port}}/test/commit/1?test_id=123
###
POST {{protocol}}://{{url}}:{{port}}/test/project/1
###
GET {{protocol}}://{{url}}:{{port}}/test/project/1?test_id=123