PUT http://localhost:8000/project/register HTTP/1.1
content-type: application/json

{
    "config": "asdf"
}
###
DELETE http://localhost:8000/project/delete/123 HTTP/1.1
###


PUT http://localhost:8000/config/add/0 HTTP/1.1
content-type: application/json

{
    "config": "asdf"
}
###
GET http://localhost:8000/config/get/1?config_id=123
###
GET http://localhost:8000/config/get_all/1
###


POST http://localhost:8000/test/commit/1?commit=cc46701e747d855807c26252c90b628c9cd319cc HTTP/1.1
###
GET http://localhost:8000/test/commit/1?test_id=123 HTTP/1.1
###
POST http://localhost:8000/test/project/1 HTTP/1.1
###
GET http://localhost:8000/test/project/1?test_id=123 HTTP/1.1