---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-orchestrator
  namespace: cdpb-tester
  labels:
    app: test-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-orchestrator
  template:
    metadata:
      labels:
        app: test-orchestrator
    spec:
      containers:
        - name: test-orchestrator
          image: kube001.informatik.intern.uni-leipzig.de:30005/saltypeppermint/test-orchestrator:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: regcred-local
