---
apiVersion: v1
kind: Service
metadata:
  name: test-orchestrator
  namespace: cdpb-tester
spec:
  type: NodePort
  selector:
    app: test-orchestrator
  ports:
    - nodePort: 30104
      port: 8000
      protocol: TCP
      targetPort: 8000
