---
apiVersion: v1
kind: Service
metadata:
  name: cdpb-test-orchestrator
  namespace: cdpb-tester
spec:
  type: NodePort
  selector:
    app: cdpb-test-orchestrator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
