---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-orchestrator
  labels:
    app: test-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-orchestrator
  template:
    metadata:
      labels:
        app: test-orchestrator
    spec:
      containers:
        - name: test-orchestrator
          image: kube001.informatik.intern.uni-leipzig.de:30005/nicole/test-orchestrator:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: test-orchestrator
spec:
  type: NodePort
  selector:
    app: test-orchestrator
  ports:
    - nodePort: 30104
      port: 8000
      protocol: TCP
      targetPort: 8000
