NAMESPACE = "nicole-bsc"
NFS_SERVER = "oersted.informatik.uni-leipzig.de"
NFS_TARED_SHARE = "/raid/kube_storage/nicole_bsc/tared_commits"
CONTAINER_REGISTRY_URL = "kube001.informatik.intern.uni-leipzig.de:30005"
CONTAINER_REGISTRY_USER = "cbpb-tester"
KANIKO_SECRET_VOL_NAME = "kaniko-secret"
TARED_COMMITS_VOL_NAME = "tared-commits"
